-- Founder copy supplied and approved by the site owner. No invented portraits or links.
INSERT INTO "TeamMember" ("id","slug","name","category","published","isDemo","order","publishedAt","updatedAt") VALUES ('kateryna-hannouf','kateryna-hannouf','KATERYNA HANNOUF','LEADERSHIP',true,false,0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name", "category"='LEADERSHIP', "published"=true, "isDemo"=false, "order"=EXCLUDED."order", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'kateryna-hannouf-en',"id",'EN','KATERYNA HANNOUF','President, PhD','President of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), PhD, international expert in innovation, digital transformation, and international cooperation. Founder and leader of international scientific and educational initiatives aimed at strengthening cooperation between Ukraine and the European Union.

She actively participates in international expert consultations on artificial intelligence regulation and digital governance. She is the author of expert recommendations on digital transformation, the ethical use of artificial intelligence, and innovation-driven development. A regular participant in international forums, conferences, and hackathons dedicated to artificial intelligence and emerging technologies, including the International AI Hackathon in New York (2025) and Paris (2026). She coordinates international partnerships, science diplomacy projects, and the Institute’s strategic initiatives aimed at integrating Ukrainian science into the European and global research community.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='kateryna-hannouf' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'kateryna-hannouf-fr',"id",'FR','KATERYNA HANNOUF','President, PhD','President of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), PhD, international expert in innovation, digital transformation, and international cooperation. Founder and leader of international scientific and educational initiatives aimed at strengthening cooperation between Ukraine and the European Union.

She actively participates in international expert consultations on artificial intelligence regulation and digital governance. She is the author of expert recommendations on digital transformation, the ethical use of artificial intelligence, and innovation-driven development. A regular participant in international forums, conferences, and hackathons dedicated to artificial intelligence and emerging technologies, including the International AI Hackathon in New York (2025) and Paris (2026). She coordinates international partnerships, science diplomacy projects, and the Institute’s strategic initiatives aimed at integrating Ukrainian science into the European and global research community.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='kateryna-hannouf' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'kateryna-hannouf-uk',"id",'UK','KATERYNA HANNOUF','President, PhD','President of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), PhD, international expert in innovation, digital transformation, and international cooperation. Founder and leader of international scientific and educational initiatives aimed at strengthening cooperation between Ukraine and the European Union.

She actively participates in international expert consultations on artificial intelligence regulation and digital governance. She is the author of expert recommendations on digital transformation, the ethical use of artificial intelligence, and innovation-driven development. A regular participant in international forums, conferences, and hackathons dedicated to artificial intelligence and emerging technologies, including the International AI Hackathon in New York (2025) and Paris (2026). She coordinates international partnerships, science diplomacy projects, and the Institute’s strategic initiatives aimed at integrating Ukrainian science into the European and global research community.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='kateryna-hannouf' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMember" ("id","slug","name","category","published","isDemo","order","publishedAt","updatedAt") VALUES ('liudmyla-golovkova','liudmyla-golovkova','LIUDMYLA GOLOVKOVA','LEADERSHIP',true,false,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name", "category"='LEADERSHIP', "published"=true, "isDemo"=false, "order"=EXCLUDED."order", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'liudmyla-golovkova-en',"id",'EN','LIUDMYLA GOLOVKOVA','Co-Founder, Doctor of Economics, Professor','Co-Founder of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), Doctor of Economics, Professor, and Academician of the Academy of Economic Sciences of Ukraine.

A distinguished Ukrainian scholar in the fields of economics, management, human capital development, and organizational studies. She is the author of numerous scientific publications, monographs, textbooks, and methodological works. Editor-in-Chief of the international scientific journal “Synergies Scientifiques”. With extensive experience in academic, research, and managerial activities, she actively contributes to the development of international academic cooperation and the integration of Ukrainian science into the European Research Area. Within the Institute, she is responsible for scientific programs, international academic relations, and research projects.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='liudmyla-golovkova' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'liudmyla-golovkova-fr',"id",'FR','LIUDMYLA GOLOVKOVA','Co-Founder, Doctor of Economics, Professor','Co-Founder of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), Doctor of Economics, Professor, and Academician of the Academy of Economic Sciences of Ukraine.

A distinguished Ukrainian scholar in the fields of economics, management, human capital development, and organizational studies. She is the author of numerous scientific publications, monographs, textbooks, and methodological works. Editor-in-Chief of the international scientific journal “Synergies Scientifiques”. With extensive experience in academic, research, and managerial activities, she actively contributes to the development of international academic cooperation and the integration of Ukrainian science into the European Research Area. Within the Institute, she is responsible for scientific programs, international academic relations, and research projects.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='liudmyla-golovkova' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'liudmyla-golovkova-uk',"id",'UK','LIUDMYLA GOLOVKOVA','Co-Founder, Doctor of Economics, Professor','Co-Founder of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), Doctor of Economics, Professor, and Academician of the Academy of Economic Sciences of Ukraine.

A distinguished Ukrainian scholar in the fields of economics, management, human capital development, and organizational studies. She is the author of numerous scientific publications, monographs, textbooks, and methodological works. Editor-in-Chief of the international scientific journal “Synergies Scientifiques”. With extensive experience in academic, research, and managerial activities, she actively contributes to the development of international academic cooperation and the integration of Ukrainian science into the European Research Area. Within the Institute, she is responsible for scientific programs, international academic relations, and research projects.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='liudmyla-golovkova' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMember" ("id","slug","name","category","published","isDemo","order","publishedAt","updatedAt") VALUES ('glib-vysheslavsky','glib-vysheslavsky','GLIB VYSHESLAVSKY','LEADERSHIP',true,false,2,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name", "category"='LEADERSHIP', "published"=true, "isDemo"=false, "order"=EXCLUDED."order", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'glib-vysheslavsky-en',"id",'EN','GLIB VYSHESLAVSKY','Co-Founder, Doctor of Art Studies, Professor','Co-Founder of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), Doctor of Art Studies, Professor, Associate Professor at Sorbonne University, renowned Ukrainian art historian, curator, and researcher of contemporary art.

Author of numerous scholarly publications and monographs on the history, theory, and philosophy of art. He has been actively involved in international academic and cultural projects promoting intercultural dialogue and the international visibility of Ukrainian culture. Within the Institute, he coordinates research in the humanities, cultural diplomacy initiatives, and international cooperation in the fields of art and cultural heritage.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='glib-vysheslavsky' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'glib-vysheslavsky-fr',"id",'FR','GLIB VYSHESLAVSKY','Co-Founder, Doctor of Art Studies, Professor','Co-Founder of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), Doctor of Art Studies, Professor, Associate Professor at Sorbonne University, renowned Ukrainian art historian, curator, and researcher of contemporary art.

Author of numerous scholarly publications and monographs on the history, theory, and philosophy of art. He has been actively involved in international academic and cultural projects promoting intercultural dialogue and the international visibility of Ukrainian culture. Within the Institute, he coordinates research in the humanities, cultural diplomacy initiatives, and international cooperation in the fields of art and cultural heritage.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='glib-vysheslavsky' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'glib-vysheslavsky-uk',"id",'UK','GLIB VYSHESLAVSKY','Co-Founder, Doctor of Art Studies, Professor','Co-Founder of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), Doctor of Art Studies, Professor, Associate Professor at Sorbonne University, renowned Ukrainian art historian, curator, and researcher of contemporary art.

Author of numerous scholarly publications and monographs on the history, theory, and philosophy of art. He has been actively involved in international academic and cultural projects promoting intercultural dialogue and the international visibility of Ukrainian culture. Within the Institute, he coordinates research in the humanities, cultural diplomacy initiatives, and international cooperation in the fields of art and cultural heritage.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='glib-vysheslavsky' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMember" ("id","slug","name","category","published","isDemo","order","publishedAt","updatedAt") VALUES ('anna-golovkova','anna-golovkova','ANNA GOLOVKOVA','LEADERSHIP',true,false,3,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name", "category"='LEADERSHIP', "published"=true, "isDemo"=false, "order"=EXCLUDED."order", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'anna-golovkova-en',"id",'EN','ANNA GOLOVKOVA','Co-Founder, Entrepreneur, Certified IPS Business Coach','Co-Founder of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), entrepreneur, Co-Founder and Managing Director of the international digital agency WebVision360 (Paris, France), and Certified IPS Business Coach.

She specializes in digital communications, branding, business development, strategic marketing, and international project management. She has extensive experience in supporting digital transformation processes and building international partnerships. Within the Institute, she contributes to the implementation of innovative projects, the development of digital infrastructure, and the promotion of international scientific and educational initiatives.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='anna-golovkova' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'anna-golovkova-fr',"id",'FR','ANNA GOLOVKOVA','Co-Founder, Entrepreneur, Certified IPS Business Coach','Co-Founder of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), entrepreneur, Co-Founder and Managing Director of the international digital agency WebVision360 (Paris, France), and Certified IPS Business Coach.

She specializes in digital communications, branding, business development, strategic marketing, and international project management. She has extensive experience in supporting digital transformation processes and building international partnerships. Within the Institute, she contributes to the implementation of innovative projects, the development of digital infrastructure, and the promotion of international scientific and educational initiatives.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='anna-golovkova' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'anna-golovkova-uk',"id",'UK','ANNA GOLOVKOVA','Co-Founder, Entrepreneur, Certified IPS Business Coach','Co-Founder of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), entrepreneur, Co-Founder and Managing Director of the international digital agency WebVision360 (Paris, France), and Certified IPS Business Coach.

She specializes in digital communications, branding, business development, strategic marketing, and international project management. She has extensive experience in supporting digital transformation processes and building international partnerships. Within the Institute, she contributes to the implementation of innovative projects, the development of digital infrastructure, and the promotion of international scientific and educational initiatives.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='anna-golovkova' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMember" ("id","slug","name","category","published","isDemo","order","publishedAt","updatedAt") VALUES ('volodymyr-kohutiak','volodymyr-kohutiak','VOLODYMYR KOHUTIAK','LEADERSHIP',true,false,4,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO UPDATE SET "name"=EXCLUDED."name", "category"='LEADERSHIP', "published"=true, "isDemo"=false, "order"=EXCLUDED."order", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'volodymyr-kohutiak-en',"id",'EN','VOLODYMYR KOHUTIAK','Co-Founder, Public Affairs Expert','Co-Founder of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), public affairs expert, Vice-President of the Ukrainian Congress in France, and Vice-President of the Union of Ukrainians in France.

He actively promotes Ukrainian-French cooperation, supports the Ukrainian community abroad, and contributes to the implementation of international humanitarian and cultural initiatives. He represents the interests of the Ukrainian diaspora in France and works to strengthen cooperation between Ukrainian and European institutions. In 2025, he was appointed Advisor to the Ukrainian Parliament Commissioner for Human Rights (Ombudsman) in the French Republic.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='volodymyr-kohutiak' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'volodymyr-kohutiak-fr',"id",'FR','VOLODYMYR KOHUTIAK','Co-Founder, Public Affairs Expert','Co-Founder of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), public affairs expert, Vice-President of the Ukrainian Congress in France, and Vice-President of the Union of Ukrainians in France.

He actively promotes Ukrainian-French cooperation, supports the Ukrainian community abroad, and contributes to the implementation of international humanitarian and cultural initiatives. He represents the interests of the Ukrainian diaspora in France and works to strengthen cooperation between Ukrainian and European institutions. In 2025, he was appointed Advisor to the Ukrainian Parliament Commissioner for Human Rights (Ombudsman) in the French Republic.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='volodymyr-kohutiak' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
INSERT INTO "TeamMemberTranslation" ("id","teamMemberId","locale","displayName","role","biography","updatedAt") SELECT 'volodymyr-kohutiak-uk',"id",'UK','VOLODYMYR KOHUTIAK','Co-Founder, Public Affairs Expert','Co-Founder of the Ukrainian-French Institute of Science, Innovation and Economic Development (UFDE, France), public affairs expert, Vice-President of the Ukrainian Congress in France, and Vice-President of the Union of Ukrainians in France.

He actively promotes Ukrainian-French cooperation, supports the Ukrainian community abroad, and contributes to the implementation of international humanitarian and cultural initiatives. He represents the interests of the Ukrainian diaspora in France and works to strengthen cooperation between Ukrainian and European institutions. In 2025, he was appointed Advisor to the Ukrainian Parliament Commissioner for Human Rights (Ombudsman) in the French Republic.',CURRENT_TIMESTAMP FROM "TeamMember" WHERE "slug"='volodymyr-kohutiak' ON CONFLICT ("teamMemberId","locale") DO UPDATE SET "displayName"=EXCLUDED."displayName", "role"=EXCLUDED."role", "biography"=EXCLUDED."biography", "updatedAt"=CURRENT_TIMESTAMP;
