import 'server-only';
import {cache} from 'react';
import {institute,type Locale} from '@ufde/config';
import {demoRecords} from '@ufde/config/demo';
import {dictionary,type PageKey} from '@ufde/config/messages';
import type {ContentRecord,ContentKind} from '@ufde/types';
export const demoMode=process.env.NEXT_PUBLIC_DEMO_MODE!=='false';
const api=process.env.API_INTERNAL_URL||process.env.NEXT_PUBLIC_API_URL;
async function request(path:string){if(!api)throw new Error('Content API is not configured');const r=await fetch(api+(process.env.CMS_LEGACY_CONTENT==='true'?'':'/cms-public')+path,{next:{revalidate:60},signal:AbortSignal.timeout(6000)});if(r.status===404)return null;if(!r.ok)throw new Error('Content is unavailable');return r.json();}
export const listContent=cache(async(kind:ContentKind,locale:Locale):Promise<ContentRecord[]>=>{if(demoMode)return demoRecords.filter(r=>r.kind===kind&&r.locale===locale);const rows:ContentRecord[]=[];for(let offset=0;offset<10000;offset+=100){const batch=await request('/content?kind='+kind+'&locale='+locale+'&limit=100&offset='+offset);rows.push(...batch);if(batch.length<100)break;}return rows;});
export const getContent=cache(async(slug:string,locale:Locale,kind?:ContentKind):Promise<ContentRecord|null>=>demoMode?demoRecords.find(r=>r.slug===slug&&r.locale===locale&&(!kind||r.kind===kind))||null:request('/content/'+encodeURIComponent(slug)+'?locale='+locale+(kind?'&kind='+kind:'')));
export const getPage=cache(async(key:PageKey,locale:Locale):Promise<string[]>=>{const fallback=dictionary(locale).pages[key];if(demoMode)return fallback;const page=await request('/pages/'+key+'?locale='+locale);return Array.isArray(page?.blocks)?page.blocks:fallback;});
export const getTeam=cache(async(locale:Locale):Promise<import('@ufde/types').TeamProfile[]>=>{if(demoMode)return [];const rows:import('@ufde/types').TeamProfile[]=[];for(let offset=0;offset<10000;offset+=100){const batch=await request('/team?locale='+locale+'&limit=100&offset='+offset);rows.push(...batch);if(batch.length<100)break;}return rows.filter(r=>(r.category==='leadership'||r.category==='advisory')&&r.role).map(r=>({...r,expertise:r.expertise||[],photoUrl:r.photoUrl?safeImage(r.photoUrl)||undefined:undefined}));});
export function safeImage(url:string){if(/^\/api\/media\/[a-f0-9-]{36}$/.test(url)||/^\/images\/[a-zA-Z0-9/_\-.]+$/.test(url))return url;try{const u=new URL(url);const hosts=(process.env.NEXT_PUBLIC_IMAGE_HOSTS||'').split(',');if(u.protocol==='https:'&&hosts.includes(u.hostname))return url;}catch{}return null;}
export const getHero=cache(async()=>{const fallback={...institute.hero,src:String(institute.hero.src),alt:String(institute.hero.alt)};if(demoMode)return fallback;const settings=await request('/settings');const hero=settings?.hero;if(hero&&safeImage(hero.url))return {...fallback,src:hero.url,alt:hero.alt,credit:hero.credit||'',source:hero.url,license:hero.licenseUrl||''};return fallback;});

export const getPartners=cache(async(locale:Locale='en'):Promise<import('@ufde/types').Partner[]>=>{if(demoMode)return [];const rows:import('@ufde/types').Partner[]=await request('/partners?locale='+locale)||[];return rows.filter(p=>p.published===true&&p.logo&&safeImage(p.logo.url)).sort((a,b)=>a.sortOrder-b.sortOrder);});
export const getPartnerLabel=cache(async(locale:Locale):Promise<string>=>{const {partnerLabelOptions,partnerLabels}=await import('@ufde/config/partners');const label=demoMode?'Our Partners':(await request('/settings'))?.partnerPresentation?.label;const i=partnerLabelOptions.indexOf(label);return partnerLabels[locale][i<0?0:i];});

export const getAboutProfile=cache(async():Promise<import('@ufde/config/about').AboutProfile>=>{const {aboutProfile}=await import('@ufde/config/about');if(demoMode)return aboutProfile;const settings=await request('/settings');const profile:import('@ufde/config/about').AboutProfile=settings?.aboutProfile || aboutProfile;const photos=profile.photos.filter(p=>safeImage(p.url));return {...profile,photos:photos.length?photos:aboutProfile.photos};});

export const getActivityDetails=cache(async(slug:string,locale:Locale):Promise<import('@ufde/types').ActivityDetails>=>{const empty={gallery:[],partners:[]};if(demoMode)return empty;const value=await request('/activity-details/'+encodeURIComponent(slug)+'?locale='+locale)||empty;return {...value,partners:value.partners.filter((p:import('@ufde/types').Partner)=>p.published&&p.logo&&safeImage(p.logo.url))};});

export const getProjectDetails=cache(async(slug:string,locale:Locale):Promise<import('@ufde/types').ProjectDetails>=>{const {emptyProjectDetails,projectCategoryKeys}=await import('@ufde/config/projects');if(demoMode){const rows=demoRecords.filter(r=>r.kind==='PROJECT'&&r.locale===locale);const index=rows.findIndex(r=>r.slug===slug),record=rows[index];return {...emptyProjectDetails,status:'Planned',category:projectCategoryKeys[Math.max(0,index)],startDate:record?.startDate||undefined,endDate:record?.endDate||undefined,background:record?.body,featured:index===0};}const value=await request('/project-details/'+encodeURIComponent(slug)+'?locale='+locale)||emptyProjectDetails;return {...value,partners:value.partners.filter((p:import('@ufde/types').Partner)=>p.published&&p.logo&&safeImage(p.logo.url))};});
export const getProjects=cache(async(locale:Locale):Promise<import('@ufde/types').ProjectView[]>=>{const records=await listContent('PROJECT',locale);return Promise.all(records.map(async r=>({record:{...r,image:r.image&&safeImage(r.image.url)?r.image:null},details:await getProjectDetails(r.slug,locale)})));});

export const listPublications=cache(async(locale:Locale):Promise<import('@ufde/types').Publication[]>=>{if(demoMode)return [];const rows:import('@ufde/types').Publication[]=[];for(let offset=0;offset<10000;offset+=100){const batch=await request('/publications?locale='+locale+'&limit=100&offset='+offset);rows.push(...batch);if(batch.length<100)break;}return rows.filter(p=>p.status==='Published'&&!p.isDemo).map(p=>({...p,coverImage:p.coverImage&&safeImage(p.coverImage.url)?p.coverImage:undefined})).sort((a,b)=>(b.publishedAt||String(b.year||0)).localeCompare(a.publishedAt||String(a.year||0)));});
export const getPublication=cache(async(slug:string,locale:Locale):Promise<import('@ufde/types').Publication|null>=>{if(demoMode)return null;const p:import('@ufde/types').Publication|null=await request('/publications/'+encodeURIComponent(slug)+'?locale='+locale);return p?.status==='Published'&&!p.isDemo?{...p,coverImage:p.coverImage&&safeImage(p.coverImage.url)?p.coverImage:undefined}:null;});

export const getGovernance=cache(async(locale:Locale):Promise<import('@ufde/types').GovernanceContent>=>{const {defaultGovernance}=await import('@ufde/config/governance');if(demoMode)return defaultGovernance(locale);const g=await request('/governance?locale='+locale)||defaultGovernance(locale);return {...g,documents:g.documents.filter((doc:import('@ufde/types').GovernanceDocument)=>doc.public)};});

export const getSocialLinks=cache(async():Promise<{network:string;url:string}[]>=>{if(demoMode)return [];const settings=await request('/settings');return (settings?.socialLinks||[]).filter((s:{network:string;url:string})=>['LinkedIn','Facebook','X','Instagram','YouTube'].includes(s.network)&&/^https:\/\//.test(s.url));});

export const getWebsiteSettings=cache(async(locale:Locale):Promise<{siteName?:string;address?:string;email?:string;phone?:string;footerText?:string}>=>demoMode?{}:await request('/settings?locale='+locale)||{});
export const getPageSEO=cache(async(slug:string,locale:Locale)=>demoMode?null:request('/seo/'+encodeURIComponent(slug)+'?locale='+locale));

export const getStrategicAreas=cache(async(locale:Locale):Promise<{slug:string;title:string;description:string;body:string;index:number}[]>=>{if(demoMode||process.env.CMS_LEGACY_CONTENT==='true'){const {strategicAreas}=await import('@ufde/config/strategic-areas');return strategicAreas(locale);}return (await request('/strategic-areas?locale='+locale)||[]).map((r:{slug:string;title:string;summary:string;body?:string},index:number)=>({slug:r.slug,title:r.title,description:r.summary,body:r.body||'',index:index%6}));});
