import type {Locale} from './index';
export const activityCategoryKeys=['conferences-events','scientific-cooperation','education-training','policy-development','culture-arts'] as const;
export const activityLabels={
 en:{title:'Our Activities',subtitle:'Conferences, meetings, training and initiatives that foster dialogue and change.',all:'All',categories:['Conferences & Events','Scientific Cooperation','Education & Training','Policy & Development','Culture & Arts'],date:'Date',location:'Location',category:'Category',gallery:'Photo gallery',partners:'Partners',related:'Related activities',pending:'To be confirmed',noPhotos:'No photographs published yet.',noPartners:'No partners published for this activity.',noResults:'No activities in this category yet.',programme:'Download programme PDF',register:'Registration / event website',previous:'Previous activities',next:'Next activities',page:'Carousel page',demo:'Demonstration content — not an actual event.',photo:'Illustrative photograph'},
 fr:{title:'Nos activités',subtitle:'Conférences, rencontres, formations et initiatives qui favorisent le dialogue et le changement.',all:'Toutes',categories:['Conférences et événements','Coopération scientifique','Éducation et formation','Politiques et développement','Culture et arts'],date:'Date',location:'Lieu',category:'Catégorie',gallery:'Galerie photo',partners:'Partenaires',related:'Activités associées',pending:'À confirmer',noPhotos:'Aucune photographie publiée pour le moment.',noPartners:'Aucun partenaire publié pour cette activité.',noResults:'Aucune activité dans cette catégorie pour le moment.',programme:'Télécharger le programme PDF',register:'Inscription / site de l’événement',previous:'Activités précédentes',next:'Activités suivantes',page:'Page du carrousel',demo:'Contenu de démonstration — ceci n’est pas un événement réel.',photo:'Photographie illustrative'},
 uk:{title:'Наші заходи',subtitle:'Конференції, зустрічі, навчання та ініціативи, що сприяють діалогу та змінам.',all:'Усі',categories:['Конференції та події','Наукова співпраця','Освіта та навчання','Політика та розвиток','Культура та мистецтво'],date:'Дата',location:'Місце',category:'Категорія',gallery:'Фотогалерея',partners:'Партнери',related:'Пов’язані заходи',pending:'Буде уточнено',noPhotos:'Фотографій поки не опубліковано.',noPartners:'Партнерів цього заходу поки не опубліковано.',noResults:'У цій категорії поки немає заходів.',programme:'Завантажити програму PDF',register:'Реєстрація / сайт події',previous:'Попередні заходи',next:'Наступні заходи',page:'Сторінка каруселі',demo:'Демонстраційний вміст — це не реальна подія.',photo:'Ілюстративне фото'}
};
export function categoryLabel(category:string,locale:Locale){const index=activityCategoryKeys.indexOf(category as typeof activityCategoryKeys[number]);return index<0?category:activityLabels[locale].categories[index];}
export function categoryKey(category:string){const index=activityCategoryKeys.findIndex((key,i)=>key===category||Object.values(activityLabels).some(l=>l.categories[i]===category));return index<0?category:activityCategoryKeys[index];}
