import type {ContentRecord} from '@ufde/types';
export const demoRecords:ContentRecord[]=[
  {
    "id": "demo-scientific-dialogue-en",
    "slug": "demo-scientific-dialogue",
    "kind": "ACTIVITY",
    "locale": "en",
    "title": "Scientific dialogue — example format",
    "summary": "An illustrative record for previewing the website. This is not an actual institutional activity, project or publication.",
    "body": "This demonstration shows how approved material will appear on the UFDE website.\n\nNo event, participant, partner, funding, research finding or publication is represented by this example. Replace this record with verified content through the content API before public launch.",
    "category": "Science & research",
    "isDemo": true,
    "publishedAt": null,
    "image": null
  },
  {
    "id": "demo-knowledge-exchange-en",
    "slug": "demo-knowledge-exchange",
    "kind": "PROJECT",
    "locale": "en",
    "title": "Knowledge exchange — example format",
    "summary": "An illustrative record for previewing the website. This is not an actual institutional activity, project or publication.",
    "body": "This demonstration shows how approved material will appear on the UFDE website.\n\nNo event, participant, partner, funding, research finding or publication is represented by this example. Replace this record with verified content through the content API before public launch.",
    "category": "Innovation & knowledge",
    "isDemo": true,
    "publishedAt": null,
    "image": null
  },
  {
    "id": "demo-european-perspectives-en",
    "slug": "demo-european-perspectives",
    "kind": "PUBLICATION",
    "locale": "en",
    "title": "European perspectives — example format",
    "summary": "An illustrative record for previewing the website. This is not an actual institutional activity, project or publication.",
    "body": "This demonstration shows how approved material will appear on the UFDE website.\n\nNo event, participant, partner, funding, research finding or publication is represented by this example. Replace this record with verified content through the content API before public launch.",
    "category": "European development",
    "isDemo": true,
    "publishedAt": null,
    "image": null
  },
  {
    "id": "demo-scientific-dialogue-fr",
    "slug": "demo-scientific-dialogue",
    "kind": "ACTIVITY",
    "locale": "fr",
    "title": "Dialogue scientifique — exemple de format",
    "summary": "Un exemple destiné à la prévisualisation du site. Il ne s’agit pas d’une activité, d’un projet ou d’une publication réels.",
    "body": "Cette démonstration présente l’affichage des futurs contenus approuvés sur le site UFDE.\n\nCet exemple ne représente aucun événement, participant, partenaire, financement, résultat de recherche ou publication. Remplacez-le par un contenu vérifié avant le lancement public.",
    "category": "Science et recherche",
    "isDemo": true,
    "publishedAt": null,
    "image": null
  },
  {
    "id": "demo-knowledge-exchange-fr",
    "slug": "demo-knowledge-exchange",
    "kind": "PROJECT",
    "locale": "fr",
    "title": "Échange de connaissances — exemple de format",
    "summary": "Un exemple destiné à la prévisualisation du site. Il ne s’agit pas d’une activité, d’un projet ou d’une publication réels.",
    "body": "Cette démonstration présente l’affichage des futurs contenus approuvés sur le site UFDE.\n\nCet exemple ne représente aucun événement, participant, partenaire, financement, résultat de recherche ou publication. Remplacez-le par un contenu vérifié avant le lancement public.",
    "category": "Innovation et savoir",
    "isDemo": true,
    "publishedAt": null,
    "image": null
  },
  {
    "id": "demo-european-perspectives-fr",
    "slug": "demo-european-perspectives",
    "kind": "PUBLICATION",
    "locale": "fr",
    "title": "Perspectives européennes — exemple de format",
    "summary": "Un exemple destiné à la prévisualisation du site. Il ne s’agit pas d’une activité, d’un projet ou d’une publication réels.",
    "body": "Cette démonstration présente l’affichage des futurs contenus approuvés sur le site UFDE.\n\nCet exemple ne représente aucun événement, participant, partenaire, financement, résultat de recherche ou publication. Remplacez-le par un contenu vérifié avant le lancement public.",
    "category": "Développement européen",
    "isDemo": true,
    "publishedAt": null,
    "image": null
  },
  {
    "id": "demo-scientific-dialogue-uk",
    "slug": "demo-scientific-dialogue",
    "kind": "ACTIVITY",
    "locale": "uk",
    "title": "Науковий діалог — приклад формату",
    "summary": "Приклад для попереднього перегляду сайту. Це не реальна діяльність, проєкт або публікація інституту.",
    "body": "Цей приклад показує, як затверджені матеріали виглядатимуть на сайті UFDE.\n\nВін не представляє подію, учасника, партнера, фінансування, результат дослідження або публікацію. Перед публічним запуском замініть його перевіреними матеріалами.",
    "category": "Наука та дослідження",
    "isDemo": true,
    "publishedAt": null,
    "image": null
  },
  {
    "id": "demo-knowledge-exchange-uk",
    "slug": "demo-knowledge-exchange",
    "kind": "PROJECT",
    "locale": "uk",
    "title": "Обмін знаннями — приклад формату",
    "summary": "Приклад для попереднього перегляду сайту. Це не реальна діяльність, проєкт або публікація інституту.",
    "body": "Цей приклад показує, як затверджені матеріали виглядатимуть на сайті UFDE.\n\nВін не представляє подію, учасника, партнера, фінансування, результат дослідження або публікацію. Перед публічним запуском замініть його перевіреними матеріалами.",
    "category": "Інновації та знання",
    "isDemo": true,
    "publishedAt": null,
    "image": null
  },
  {
    "id": "demo-european-perspectives-uk",
    "slug": "demo-european-perspectives",
    "kind": "PUBLICATION",
    "locale": "uk",
    "title": "Європейські перспективи — приклад формату",
    "summary": "Приклад для попереднього перегляду сайту. Це не реальна діяльність, проєкт або публікація інституту.",
    "body": "Цей приклад показує, як затверджені матеріали виглядатимуть на сайті UFDE.\n\nВін не представляє подію, учасника, партнера, фінансування, результат дослідження або публікацію. Перед публічним запуском замініть його перевіреними матеріалами.",
    "category": "Європейський розвиток",
    "isDemo": true,
    "publishedAt": null,
    "image": null
  }
];
