import type {Locale} from './index';
import type {ProjectDetails} from '@ufde/types';
export const projectCategoryKeys=['research-innovation','education-training','policy-development','international-cooperation','culture-creative-industries'] as const;
export const emptyProjectDetails:ProjectDetails={countries:[],partners:[],objectives:[],activities:[],outcomes:[],resources:[],relatedActivitySlugs:[],featured:false};
export const projectLabels={
 en:{title:'Our Projects',subtitle:'From ideas to impact.\nBuilding a more resilient, innovative and European Ukraine.',all:'All Projects',categories:['Research & Innovation','Education & Training','Policy & Development','International Cooperation','Culture & Creative Industries'],statuses:{Ongoing:'Ongoing',Upcoming:'Upcoming',Completed:'Completed',Planned:'Planned'},period:'Project period',partners:'Partners',area:'Strategic area',lead:'Lead',countries:'Countries',background:'Background',objectives:'Objectives',activities:'Activities',outcomes:'Expected Outcomes / Results',resources:'Publications & Resources',related:'Related Activities',contact:'Contact',featured:'FEATURED PROJECT',view:'VIEW PROJECT DETAILS',cta:'Interested in collaborating?',ctaText:'We are always open to new partnerships and project opportunities.',ctaButton:'GET IN TOUCH',pending:'To be confirmed',empty:'No projects in this category yet.',unpublished:'Information will be published when confirmed.',demo:'Demonstration project — not an actual UFDE project.',photo:'Illustrative photograph',institution:'Partner / institution type'},
 fr:{title:'Nos projets',subtitle:'Des idées à l’impact.\nConstruire une Ukraine plus résiliente, innovante et européenne.',all:'Tous les projets',categories:['Recherche et innovation','Éducation et formation','Politiques et développement','Coopération internationale','Culture et industries créatives'],statuses:{Ongoing:'En cours',Upcoming:'À venir',Completed:'Terminé',Planned:'Prévu'},period:'Période du projet',partners:'Partenaires',area:'Domaine stratégique',lead:'Responsable',countries:'Pays',background:'Contexte',objectives:'Objectifs',activities:'Activités',outcomes:'Résultats attendus / Résultats',resources:'Publications et ressources',related:'Activités associées',contact:'Contact',featured:'PROJET À LA UNE',view:'VOIR LE PROJET',cta:'Envie de collaborer ?',ctaText:'Nous sommes toujours ouverts à de nouveaux partenariats et projets.',ctaButton:'CONTACTEZ-NOUS',pending:'À confirmer',empty:'Aucun projet dans cette catégorie pour le moment.',unpublished:'Les informations seront publiées après confirmation.',demo:'Projet de démonstration — ce n’est pas un projet réel de l’UFDE.',photo:'Photographie illustrative',institution:'Type de partenaire / institution'},
 uk:{title:'Наші проєкти',subtitle:'Від ідей до результатів.\nРозбудовуємо стійку, інноваційну та європейську Україну.',all:'Усі проєкти',categories:['Дослідження та інновації','Освіта та навчання','Політика та розвиток','Міжнародна співпраця','Культура та креативні індустрії'],statuses:{Ongoing:'Триває',Upcoming:'Незабаром',Completed:'Завершено',Planned:'Заплановано'},period:'Період проєкту',partners:'Партнери',area:'Стратегічний напрям',lead:'Керівник',countries:'Країни',background:'Передумови',objectives:'Цілі',activities:'Заходи',outcomes:'Очікувані результати / Результати',resources:'Публікації та ресурси',related:'Пов’язані заходи',contact:'Контакти',featured:'ПРОЄКТ У ФОКУСІ',view:'ПЕРЕГЛЯНУТИ ПРОЄКТ',cta:'Зацікавлені у співпраці?',ctaText:'Ми завжди відкриті до нових партнерств та проєктних можливостей.',ctaButton:'ЗВ’ЯЖІТЬСЯ З НАМИ',pending:'Буде уточнено',empty:'У цій категорії поки немає проєктів.',unpublished:'Інформацію буде опубліковано після підтвердження.',demo:'Демонстраційний проєкт — це не реальний проєкт UFDE.',photo:'Ілюстративне фото',institution:'Тип партнера / установи'}
};
export function projectCategoryLabel(key:string,locale:Locale){const i=projectCategoryKeys.indexOf(key as typeof projectCategoryKeys[number]);return i<0?key:projectLabels[locale].categories[i];}
export function projectPeriod(p:ProjectDetails,locale:Locale){return p.startDate||p.endDate?`${p.startDate?.slice(0,4)||projectLabels[locale].pending} — ${p.endDate?.slice(0,4)||projectLabels[locale].pending}`:projectLabels[locale].pending;}
