-- Partnerships explicitly confirmed by UFDE on 20 September 2026.
INSERT INTO "Media" ("id","slug","url","filename","mimeType","sizeBytes","sha256","visibility","purpose","updatedAt") VALUES ('partner-logo-sorbonne-universite','partner-logo-sorbonne-universite','/images/partners/sorbonne-universite.svg','sorbonne-universite.svg','image/svg+xml',4903,'c787b01ac5d19cb36f2c5091e49670445b889baeecff6a0754f1d5178eb1570f','PUBLIC','LOGO',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Partner" ("id","slug","name","website","countryCode","partnerType","logoId","featured","sortOrder","published","publishedAt","isDemo","updatedAt") VALUES ('sorbonne-universite','sorbonne-universite','Sorbonne Université','https://www.sorbonne-universite.fr/','FR','ACADEMIC',(SELECT "id" FROM "Media" WHERE "slug"='partner-logo-sorbonne-universite'),true,0,true,CURRENT_TIMESTAMP,false,CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "PartnerTranslation" ("id","partnerId","locale","displayName","description","logoAlt","updatedAt") VALUES ('sorbonne-universite-en',(SELECT "id" FROM "Partner" WHERE "slug"='sorbonne-universite'),'EN','Sorbonne Université','','Sorbonne Université',CURRENT_TIMESTAMP) ON CONFLICT ("partnerId","locale") DO NOTHING;
INSERT INTO "PartnerTranslation" ("id","partnerId","locale","displayName","description","logoAlt","updatedAt") VALUES ('sorbonne-universite-fr',(SELECT "id" FROM "Partner" WHERE "slug"='sorbonne-universite'),'FR','Sorbonne Université','','Sorbonne Université',CURRENT_TIMESTAMP) ON CONFLICT ("partnerId","locale") DO NOTHING;
INSERT INTO "PartnerTranslation" ("id","partnerId","locale","displayName","description","logoAlt","updatedAt") VALUES ('sorbonne-universite-uk',(SELECT "id" FROM "Partner" WHERE "slug"='sorbonne-universite'),'UK','Sorbonne Université','','Sorbonne Université',CURRENT_TIMESTAMP) ON CONFLICT ("partnerId","locale") DO NOTHING;
INSERT INTO "Media" ("id","slug","url","filename","mimeType","sizeBytes","sha256","visibility","purpose","updatedAt") VALUES ('partner-logo-ukraine-embassy-france','partner-logo-ukraine-embassy-france','/images/partners/ukraine-embassy-france.jpg','ukraine-embassy-france.jpg','image/jpeg',12302,'eaca101944515d31f1f861bea91d5dbbb1c975a392952dff63a20efa10da2619','PUBLIC','LOGO',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Partner" ("id","slug","name","website","countryCode","partnerType","logoId","featured","sortOrder","published","publishedAt","isDemo","updatedAt") VALUES ('ukraine-embassy-france','ukraine-embassy-france','Embassy of Ukraine in France','https://france.mfa.gov.ua/','FR','INSTITUTIONAL',(SELECT "id" FROM "Media" WHERE "slug"='partner-logo-ukraine-embassy-france'),true,1,true,CURRENT_TIMESTAMP,false,CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "PartnerTranslation" ("id","partnerId","locale","displayName","description","logoAlt","updatedAt") VALUES ('ukraine-embassy-france-en',(SELECT "id" FROM "Partner" WHERE "slug"='ukraine-embassy-france'),'EN','Embassy of Ukraine in France','','Embassy of Ukraine in France',CURRENT_TIMESTAMP) ON CONFLICT ("partnerId","locale") DO NOTHING;
INSERT INTO "PartnerTranslation" ("id","partnerId","locale","displayName","description","logoAlt","updatedAt") VALUES ('ukraine-embassy-france-fr',(SELECT "id" FROM "Partner" WHERE "slug"='ukraine-embassy-france'),'FR','Ambassade d’Ukraine en France','','Ambassade d’Ukraine en France',CURRENT_TIMESTAMP) ON CONFLICT ("partnerId","locale") DO NOTHING;
INSERT INTO "PartnerTranslation" ("id","partnerId","locale","displayName","description","logoAlt","updatedAt") VALUES ('ukraine-embassy-france-uk',(SELECT "id" FROM "Partner" WHERE "slug"='ukraine-embassy-france'),'UK','Посольство України у Франції','','Посольство України у Франції',CURRENT_TIMESTAMP) ON CONFLICT ("partnerId","locale") DO NOTHING;
INSERT INTO "Media" ("id","slug","url","filename","mimeType","sizeBytes","sha256","visibility","purpose","updatedAt") VALUES ('partner-logo-zbarazh-city-council','partner-logo-zbarazh-city-council','/images/partners/zbarazh-city-council.png','zbarazh-city-council.png','image/png',78093,'ad983b2f9bfd598542db5729ed7b8bba9b5a412a05f38695e3d943677123f7ca','PUBLIC','LOGO',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "Partner" ("id","slug","name","website","countryCode","partnerType","logoId","featured","sortOrder","published","publishedAt","isDemo","updatedAt") VALUES ('zbarazh-city-council','zbarazh-city-council','Zbarazh City Council',NULL,'UA','LOCAL_AUTHORITY',(SELECT "id" FROM "Media" WHERE "slug"='partner-logo-zbarazh-city-council'),true,2,true,CURRENT_TIMESTAMP,false,CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
INSERT INTO "PartnerTranslation" ("id","partnerId","locale","displayName","description","logoAlt","updatedAt") VALUES ('zbarazh-city-council-en',(SELECT "id" FROM "Partner" WHERE "slug"='zbarazh-city-council'),'EN','Zbarazh City Council','','Zbarazh City Council',CURRENT_TIMESTAMP) ON CONFLICT ("partnerId","locale") DO NOTHING;
INSERT INTO "PartnerTranslation" ("id","partnerId","locale","displayName","description","logoAlt","updatedAt") VALUES ('zbarazh-city-council-fr',(SELECT "id" FROM "Partner" WHERE "slug"='zbarazh-city-council'),'FR','Conseil municipal de Zbarazh','','Conseil municipal de Zbarazh',CURRENT_TIMESTAMP) ON CONFLICT ("partnerId","locale") DO NOTHING;
INSERT INTO "PartnerTranslation" ("id","partnerId","locale","displayName","description","logoAlt","updatedAt") VALUES ('zbarazh-city-council-uk',(SELECT "id" FROM "Partner" WHERE "slug"='zbarazh-city-council'),'UK','Збаразька міська рада','','Збаразька міська рада',CURRENT_TIMESTAMP) ON CONFLICT ("partnerId","locale") DO NOTHING;
