"use client";
import {useState,type ReactNode} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Carousel as PrimitiveCarousel,CarouselContent,CarouselItem,CarouselPrevious,CarouselNext} from '@/components/ui/carousel';
import {Pagination as PrimitivePagination,PaginationContent,PaginationItem,PaginationLink,PaginationEllipsis} from '@/components/ui/pagination';
import {EnquiryForm} from '../forms';
import {dictionary} from '@ufde/config/messages';
import type {Locale} from '@ufde/config';
import {PartnerCard,type CardProps} from '@ufde/ui';
export function CategoryTabs({items,label='Categories',variant='filled',value,onValueChange}:{items:{value:string;label:string;content:ReactNode;disabled?:boolean}[];label?:string;variant?:'filled'|'underline';value?:string;onValueChange?:(value:string)=>void}){return <Tabs value={value} defaultValue={items.find(x=>!x.disabled)?.value} onValueChange={v=>{if(typeof v==='string')onValueChange?.(v)}} className={'uf-tabs uf-tabs-'+variant}><TabsList aria-label={label} className="uf-tabs-list">{items.map(t=><TabsTrigger key={t.value} value={t.value} disabled={t.disabled} className="uf-tab">{t.label}</TabsTrigger>)}</TabsList>{items.map(t=><TabsContent key={t.value} value={t.value} className="uf-tab-panel">{t.content}</TabsContent>)}</Tabs>}
export function Carousel({slides,label='Featured content'}:{slides:ReactNode[];label?:string}){return <PrimitiveCarousel opts={{align:'start',loop:false}} className="uf-carousel" aria-label={label} tabIndex={0}><CarouselContent>{slides.map((s,i)=><CarouselItem key={i} className="uf-slide" aria-label={`${i+1} / ${slides.length}`}>{s}</CarouselItem>)}</CarouselContent>{slides.length>1&&<div className="uf-carousel-controls"><CarouselPrevious className="uf-carousel-control"/><CarouselNext className="uf-carousel-control"/></div>}</PrimitiveCarousel>}
export function PartnerCarousel({partners,label='Partners'}:{partners:(CardProps&{logo?:ReactNode})[];label?:string}){return <Carousel label={label} slides={partners.map((p,i)=><PartnerCard key={i} {...p}/>)}/>}
export function Pagination({page,totalPages,onPageChange,label='Pagination'}:{page:number;totalPages:number;onPageChange:(page:number)=>void;label?:string}){const total=Math.max(1,Math.floor(totalPages));const current=Math.max(1,Math.min(page,total));const pages=Array.from(new Set([1,current-1,current,current+1,total])).filter(n=>n>=1&&n<=total).sort((a,b)=>a-b);return <PrimitivePagination aria-label={label} className="uf-pagination"><PaginationContent><PaginationItem><button type="button" disabled={current===1} onClick={()=>onPageChange(current-1)} aria-label="Previous page">←</button></PaginationItem>{pages.map((n,i)=><PaginationItem key={n}>{i>0&&n-pages[i-1]>1&&<PaginationEllipsis/>}<PaginationLink href={'?page='+n} isActive={n===current} aria-label={'Page '+n} onClick={e=>{e.preventDefault();onPageChange(n)}}>{n}</PaginationLink></PaginationItem>)}<PaginationItem><button type="button" disabled={current===total} onClick={()=>onPageChange(current+1)} aria-label="Next page">→</button></PaginationItem></PaginationContent></PrimitivePagination>}
type FormProps={locale?:Locale;demo:boolean};
export function NewsletterForm({locale='en',demo}:FormProps){return <EnquiryForm locale={locale} d={dictionary(locale).form} demo={demo} newsletter/>}
export function ContactForm({locale='en',demo}:FormProps){return <EnquiryForm locale={locale} d={dictionary(locale).form} demo={demo}/>}
export function PaginationExample(){const [page,setPage]=useState(1);return <><p aria-live="polite">Example results — page {page} of 8</p><Pagination page={page} totalPages={8} onPageChange={setPage}/></>}
