import {Controller,Get,Query,Param,NotFoundException} from '@nestjs/common';
import {ConfigService} from '@nestjs/config';
import {ApiTags} from '@nestjs/swagger';
import {PartnersService} from './partners.service';
import {PrismaService} from './prisma.service';
import {ListQuery} from './dto';
@ApiTags('Published content')
@Controller()
export class ContentController {
 constructor(private readonly db:PrismaService,private readonly config:ConfigService,private readonly partnerRegistry:PartnersService){}
 @Get('content') async list(@Query() q:ListQuery){if(q.kind==='PUBLICATION')return [];const rows=await this.db.content.findMany({where:{published:true,...(this.config.get('DEMO_MODE')==='true'?{}:{isDemo:false}),...(q.kind?{kind:q.kind}:{kind:{not:'PUBLICATION' as const}}),translations:{some:{locale:q.locale}}},include:{translations:{where:{locale:q.locale}},image:true},take:q.limit,skip:q.offset,orderBy:[{publishedAt:'desc'},{id:'asc'}]});return rows.map(({translations,...r})=>({...r,...translations[0],id:r.id}));}
 @Get('content/:slug') async detail(@Param('slug') slug:string,@Query() q:ListQuery){const row=await this.db.content.findFirst({where:{slug,published:true,...(this.config.get('DEMO_MODE')==='true'?{}:{isDemo:false})},include:{translations:{where:{locale:q.locale}},image:true}});if(!row || row.kind==='PUBLICATION' || !row.translations[0])throw new NotFoundException();const {translations,...r}=row;return {...r,...translations[0],id:r.id};}
 @Get('pages/:slug') async page(@Param('slug') slug:string,@Query() q:ListQuery){const page=await this.db.page.findUnique({where:{slug_locale:{slug,locale:q.locale}}});if(!page?.approved)throw new NotFoundException();return page;}
 @Get('activity-details/:slug') async activityDetails(@Param('slug') slug:string,@Query() q:ListQuery){const content=await this.db.content.findFirst({where:{slug,kind:'ACTIVITY',published:true,...(this.config.get('DEMO_MODE')==='true'?{}:{isDemo:false}),translations:{some:{locale:q.locale}}}});if(!content)throw new NotFoundException();const setting=await this.db.siteSetting.findUnique({where:{key:'activity:'+slug+':'+q.locale}});const value=(setting?.value??{gallery:[],partners:[]}) as {partners:{id:string}[]};return {...value,partners:await this.partnerRegistry.resolve(value.partners)};}
 @Get('project-details/:slug') async projectDetails(@Param('slug') slug:string,@Query() q:ListQuery){const content=await this.db.content.findFirst({where:{slug,kind:'PROJECT',published:true,...(this.config.get('DEMO_MODE')==='true'?{}:{isDemo:false}),translations:{some:{locale:q.locale}}}});if(!content)throw new NotFoundException();const setting=await this.db.siteSetting.findUnique({where:{key:'project:'+slug+':'+q.locale}});if(!setting)return null;const value=setting.value as {partners:{id:string}[]};return {...value,partners:await this.partnerRegistry.resolve(value.partners)};}
 @Get('publications') async publications(@Query() q:ListQuery){const rows=await this.db.siteSetting.findMany({where:{key:{startsWith:'publication:',endsWith:':'+q.locale},AND:[{value:{path:['status'],equals:'Published'}},{value:{path:['isDemo'],equals:false}}]},take:q.limit,skip:q.offset,orderBy:{key:'asc'}});return rows.map(r=>r.value)}
 @Get('publications/:slug') async publication(@Param('slug') slug:string,@Query() q:ListQuery){const row=await this.db.siteSetting.findUnique({where:{key:'publication:'+slug+':'+q.locale}});const p=row?.value as {status?:string;isDemo?:boolean}|undefined;if(p?.status!=='Published'||p.isDemo!==false)throw new NotFoundException();return p;}
 @Get('governance') async governance(@Query() q:ListQuery){const row=await this.db.siteSetting.findUnique({where:{key:'governance:'+q.locale}});if(!row)return null;const g=row.value as {documents:{public:boolean}[]};return {...g,documents:g.documents.filter(d=>d.public===true)};}
 @Get('partners') partners(){return this.partnerRegistry.published()}
 @Get('settings') async settings(){const setting=await this.db.siteSetting.findUnique({where:{key:'hero'}});const presentation=await this.db.siteSetting.findUnique({where:{key:'partnerPresentation'}});const profile=await this.db.siteSetting.findUnique({where:{key:'aboutProfile'}});const social=await this.db.siteSetting.findUnique({where:{key:'socialLinks'}});return {socialLinks:social?.value??[],hero:setting?.value??null,partners:await this.partnerRegistry.published(),partnerPresentation:presentation?.value??{label:'Our Partners'},aboutProfile:profile?.value??null};}
 @Get('team') async team(@Query() q:ListQuery){const rows=await this.db.teamMember.findMany({where:{published:true},orderBy:[{order:'asc'},{id:'asc'}],take:q.limit,skip:q.offset});const profiles=await this.db.siteSetting.findMany({where:{key:{in:rows.map(r=>'team:'+r.id+':'+q.locale)}}});return rows.map(r=>({...((profiles.find(p=>p.key==='team:'+r.id+':'+q.locale)?.value as Record<string,unknown>)||{}),...r,role:(r.role as Record<string,string>)[q.locale]||'',biography:(r.biography as Record<string,string>)[q.locale]||''}));}
}
