import {Injectable,Logger,OnModuleInit,OnModuleDestroy} from '@nestjs/common';
import {ConfigService} from '@nestjs/config';
import {PrismaService} from './prisma.service';
type Job={reference:string;kind:'notify'|'ack';state:string;attempts:number;nextAt:number;createdAt:number};
@Injectable()
export class ContactMailService implements OnModuleInit,OnModuleDestroy {
 private timer?:ReturnType<typeof setInterval>;private busy=false;private logger=new Logger('ContactMail');
 constructor(private db:PrismaService,private config:ConfigService){}
 onModuleInit(){this.timer=setInterval(()=>{void this.processPending().catch(()=>this.logger.warn('Mail queue temporarily unavailable'))},30000);this.timer.unref();}
 onModuleDestroy(){if(this.timer)clearInterval(this.timer)}
 async processPending(){if(this.busy||!this.config.get('RESEND_API_KEY')||!this.config.get('CONTACT_FROM_EMAIL'))return;this.busy=true;try{const jobs=await this.db.siteSetting.findMany({where:{key:{startsWith:'contact-mail:'},OR:[{value:{path:['state'],equals:'queued'}},{value:{path:['state'],equals:'processing'}}]},orderBy:{updatedAt:'asc'},take:30});for(const row of jobs){const job=await this.db.$transaction(async tx=>{await tx.$queryRaw`SELECT pg_advisory_xact_lock(hashtext(${row.key}))`;const current=(await tx.siteSetting.findUnique({where:{key:row.key}}))?.value as Job|undefined;if(!current||!['queued','processing'].includes(current.state)||current.nextAt>Date.now())return null;const next={...current,state:'processing',nextAt:Date.now()+60000};await tx.siteSetting.update({where:{key:row.key},data:{value:next}});return next});if(!job)continue;try{if(job.attempts>=6||Date.now()-job.createdAt>23*3600000)throw new Error('Expired delivery');const contact=await this.db.contactSubmission.findUnique({where:{id:job.reference}});if(!contact){await this.db.siteSetting.delete({where:{key:row.key}});continue;}const notify=job.kind==='notify';const payload={from:this.config.getOrThrow<string>('CONTACT_FROM_EMAIL'),to:[notify?(this.config.get<string>('CONTACT_NOTIFY_EMAIL')||'info@ufde.org'):contact.email],subject:notify?'UFDE website enquiry — '+job.reference:'UFDE — enquiry received',text:notify?`Reference: ${job.reference}\nName: ${contact.name}\nEmail: ${contact.email}\nOrganisation: ${contact.organization||''}\nSubject: ${contact.subject}\n\n${contact.message}`:`Thank you for contacting UFDE. Your enquiry has been received.\nReference: ${job.reference}\nOur team will review your message.`,...(notify?{reply_to:contact.email}:{})};const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+this.config.getOrThrow('RESEND_API_KEY'),'Content-Type':'application/json','Idempotency-Key':row.key},body:JSON.stringify(payload),signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error('Email delivery failed');await this.db.siteSetting.update({where:{key:row.key},data:{value:{...job,state:'sent',attempts:job.attempts+1,nextAt:0}}});}catch{const attempts=job.attempts+1,state=attempts>=6||Date.now()-job.createdAt>23*3600000?'failed':'queued';await this.db.siteSetting.update({where:{key:row.key},data:{value:{...job,state,attempts,nextAt:Date.now()+Math.min(3600000,60000*2**attempts)}}});this.logger.warn('Contact email '+state+'; reference '+job.reference);}}}finally{this.busy=false}}
}
