import Image from 'next/image';
import {Mail,MapPin,Phone} from 'lucide-react';
import {institute,type Locale} from '@ufde/config';
import {dictionary,localizedPath} from '@ufde/config/messages';
import {contactLabels} from '@ufde/config/contact';
import {Container,Section,Breadcrumbs,Heading1,Heading2,Eyebrow} from '@ufde/ui';
import {getSocialLinks,demoMode} from '@/lib/content';
import {EnquiryForm} from './forms';
export async function Contact({locale}:{locale:Locale}){const l=contactLabels[locale],d=dictionary(locale),social=await getSocialLinks().catch(()=>[]),linkedin=social.find(x=>x.network==='LinkedIn');return <div className="contact-page"><section className="contact-hero"><Image src={institute.hero.src} alt={institute.hero.alt} fill priority sizes="100vw"/><div className="contact-shade"/><Container><Breadcrumbs items={[{label:d.nav[0],href:localizedPath(locale,'')},{label:l.title}]}/><Heading1>{l.title}</Heading1><p>{l.subtitle}</p></Container></section><Section><Container><div className="contact-page-columns"><div><Eyebrow>{l.eyebrow}</Eyebrow><Heading2>{l.heading}</Heading2><p className="contact-intro">{l.text}</p><address className="contact-page-address"><p><MapPin size={21}/>{institute.location}</p><a href={'mailto:'+institute.email}><Mail size={21}/>{institute.email}</a><a href={'tel:'+institute.phone.replaceAll(' ','')}><Phone size={21}/>{institute.phone}</a>{linkedin&&<a href={linkedin.url} target="_blank" rel="noopener noreferrer">LinkedIn ↗</a>}</address>{social.length>0&&<div className="contact-social"><h3>{l.follow}</h3>{social.map(s=><a key={s.network} href={s.url} target="_blank" rel="noopener noreferrer">{s.network} ↗</a>)}</div>}</div><div className="contact-page-form"><EnquiryForm locale={locale} d={d.form} demo={demoMode}/></div></div></Container></Section><Container><p className="home-photo-credit"><a href={institute.hero.source}>{institute.hero.credit}</a> · <a href={institute.hero.license}>CC BY-SA 2.0</a> · {d.cropped}</p></Container></div>}
