"use client";
import {useState} from 'react';
import Link from 'next/link';
import {useForm} from 'react-hook-form';
import {z} from 'zod';
import {zodResolver} from '@hookform/resolvers/zod';
import {ArrowRight,CheckCircle2} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {type Locale} from '@ufde/config';
import {type Dictionary,localizedPath} from '@ufde/config/messages';
const schema=z.object({email:z.string().trim().email().max(254),name:z.string().trim().max(120).optional(),organization:z.string().trim().max(180).optional(),subject:z.string().trim().max(160).optional(),message:z.string().trim().max(5000).optional(),consent:z.literal(true),website:z.string().max(0).optional()});
type Values=z.infer<typeof schema>;
export function EnquiryForm({locale,d,newsletter=false,demo}:{locale:Locale;d:Dictionary['form'];newsletter?:boolean;demo:boolean}){const formSchema=newsletter?schema:schema.extend({name:z.string().trim().min(2).max(120),subject:z.string().trim().min(3).max(160),message:z.string().trim().min(20).max(5000)});const {register,handleSubmit,setValue,watch,formState:{errors,isSubmitting}}=useForm<Values>({resolver:zodResolver(formSchema),defaultValues:{email:'',website:''}});const [status,setStatus]=useState<'idle'|'success'|'error'>('idle');const id=newsletter?'newsletter':'contact';
async function submit(values:Values){setStatus('idle');if(demo){setStatus('success');return;}try{const url=process.env.NEXT_PUBLIC_API_URL;if(!url)throw new Error();const payload=newsletter?{email:values.email,consent:values.consent,locale,website:values.website}:{...values,locale};const result=await fetch(url+(newsletter?'/newsletter':'/contact'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(10000)});if(!result.ok)throw new Error();setStatus('success');}catch{setStatus('error')}}
if(status==='success')return <div className="form-success" role="status"><CheckCircle2 size={22}/><p>{demo?d.demoSuccess:newsletter?d.subscribed:d.success}</p></div>;
const field=(key:'name'|'email'|'organization'|'subject'|'message')=><div className="field" key={key}><label htmlFor={id+'-'+key}>{d[key]}</label>{key==='message'?<textarea id={id+'-'+key} rows={6} maxLength={5000} aria-invalid={!!errors[key]} aria-describedby={errors[key]?id+'-'+key+'-error':undefined} {...register(key)}/>:<input id={id+'-'+key} type={key==='email'?'email':'text'} autoComplete={key==='name'?'name':key==='email'?'email':key==='organization'?'organization':undefined} maxLength={key==='email'?254:key==='name'?120:key==='subject'?160:180} aria-invalid={!!errors[key]} aria-describedby={errors[key]?id+'-'+key+'-error':undefined} {...register(key)}/>} {errors[key]&&<p className="field-error" id={id+'-'+key+'-error'}>{d.invalid}</p>}</div>;
return <form noValidate onSubmit={handleSubmit(submit)} className={newsletter?'newsletter-form':'contact-form'}>{demo&&<p className="form-note">{d.demoNotice}</p>}{!newsletter&&field('name')}{field('email')}{!newsletter&&<>{field('organization')}{field('subject')}{field('message')}</>}<div className="honeypot" aria-hidden="true"><label htmlFor={id+'-website'}>Website</label><input id={id+'-website'} tabIndex={-1} autoComplete="off" {...register('website')}/></div><div className="consent-field"><Checkbox id={id+'-consent'} checked={watch('consent')===true} onCheckedChange={v=>setValue('consent',v as true,{shouldValidate:true})} aria-invalid={!!errors.consent} className="consent-checkbox"/><label htmlFor={id+'-consent'}>{newsletter?d.newsletterConsent:d.consent} <Link href={localizedPath(locale,'/privacy')}>{d.privacy}</Link></label></div>{errors.consent&&<p className="field-error">{d.invalid}</p>}{status==='error'&&<p role="alert" className="field-error">{d.error}</p>}<button className="button gold" type="submit" disabled={isSubmitting}>{isSubmitting?d.sending:newsletter?d.subscribe:d.send}<ArrowRight size={17}/></button></form>}
