import Image from 'next/image';
import {categoryLabel} from '@ufde/config/activities';
import {ArrowRight,Microscope,GraduationCap,Cpu,Handshake,Landmark,Palette} from 'lucide-react';
import {type Locale} from '@ufde/config';
import {dictionary,localizedPath} from '@ufde/config/messages';
import {Container,Section,SectionHeading,StrategicAreaCard,ActivityCard,ProjectCard,StatusBadge,PrimaryButton,OutlineButton,EmptyState} from '@ufde/ui';
import {getHero,listContent,getPartners,demoMode,safeImage} from '@/lib/content';
import {PartnerStrip} from './partner-strip';
import type {ContentRecord} from '@ufde/types';
export const areaIcons=[Microscope,GraduationCap,Cpu,Handshake,Landmark,Palette];
export async function Home({locale}:{locale:Locale}){
 const d=dictionary(locale),h=d.home,href=(p:string)=>localizedPath(locale,p);
 const [hero,activityResult,projectResult,partnerResult]=await Promise.all([getHero(),listContent('ACTIVITY',locale).then(rows=>({rows,failed:false})).catch(()=>({rows:[] as ContentRecord[],failed:true})),listContent('PROJECT',locale).then(rows=>({rows,failed:false})).catch(()=>({rows:[] as ContentRecord[],failed:true})),getPartners().then(rows=>({rows,failed:false})).catch(()=>({rows:[],failed:true}))]);
 const date=(value?:string|null)=>value?new Intl.DateTimeFormat(locale,{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(value)):h.pendingDate;
 const media=(r:ContentRecord,i:number)=>r.image&&safeImage(r.image.url)?<div className={'home-card-photo crop-'+i}><Image src={safeImage(r.image.url)!} alt={r.image.alt} width={720} height={450} sizes="(max-width:650px) 100vw, (max-width:1000px) 50vw, 33vw"/>{r.isDemo&&<span>{h.demoImage}</span>}</div>:<div className="home-media-pending"><Microscope size={36} strokeWidth={1.3}/><span>{h.pendingStatus}</span></div>;
 return <div className="ufde-home"><section className="home-hero"><Image src={hero.src} alt={hero.alt} fill priority sizes="100vw"/><div className="home-hero-shade"/><Container><p className="home-kicker">UKRAINE · FRANCE · EUROPE</p><h1>{h.headline.map(line=><span key={line}>{line}</span>)}</h1><p className="home-hero-description">{h.description}</p><div className="uf-actions"><PrimaryButton href={href('/activities')}>{h.activitiesButton}<ArrowRight size={18}/></PrimaryButton><OutlineButton className="home-hero-outline" href={href('/contact')}>{h.contactButton}</OutlineButton></div></Container><div className="home-location">PARIS, FRANCE</div></section>
 <Section><Container><SectionHeading title={h.strategic} eyebrow={h.focusEyebrow} underline/><div className="home-strategic-grid">{d.areas.map(([title,description],i)=>{const Icon=areaIcons[i];return <StrategicAreaCard key={title} title={title} description={description} icon={<Icon/>} href={href('/strategic-areas')+'#area-'+(i+1)} linkLabel={h.learn}/>})}</div></Container></Section>
 <Section tone="soft"><Container><SectionHeading title={h.activities} underline action={<a className="home-view-all" href={href('/activities')}>{h.all}<ArrowRight size={18}/></a>}/>{demoMode&&<p className="home-demo-note">{h.demoNotice}</p>}<div className="home-content-grid">{activityResult.rows.slice(0,3).map((r,i)=><ActivityCard key={r.id} title={r.title} description={r.summary} media={media(r,i)} meta={<>{r.isDemo&&<StatusBadge tone="demo">{d.demo}</StatusBadge>}<span>{r.kind==='ACTIVITY'?categoryLabel(r.category,locale):r.category}</span><span>{r.isDemo?h.dateExample+': ':''}{date(r.publishedAt)}</span></>} href={href('/activities/'+r.slug)} linkLabel={h.read}/>)}</div>{!activityResult.rows.length&&<EmptyState title={activityResult.failed?d.unavailable:d.empty}/>}</Container></Section>
 <Section><Container><SectionHeading title={h.projects} underline action={<a className="home-view-all" href={href('/projects')}>{h.all}<ArrowRight size={18}/></a>}/><div className="home-content-grid">{projectResult.rows.slice(0,3).map((r,i)=><ProjectCard key={r.id} title={r.title} description={r.summary} media={media(r,i+1)} status={r.status||h.pendingStatus} meta={r.isDemo?<StatusBadge tone="demo">{d.demo}</StatusBadge>:undefined} href={href('/projects/'+r.slug)} linkLabel={h.learn}><div className="home-project-meta"><span>{r.isDemo?h.dateExample+': ':''}{r.startDate?date(r.startDate)+' — '+date(r.endDate):h.pendingDate}</span><span>{r.kind==='ACTIVITY'?categoryLabel(r.category,locale):r.category}</span></div></ProjectCard>)}</div>{!projectResult.rows.length&&<EmptyState title={projectResult.failed?d.unavailable:d.empty}/>}</Container></Section>
 <Section tone="soft"><Container><SectionHeading title={h.partners} underline action={<a className="home-view-all" href={href('/partners')}>{h.allPartners}<ArrowRight size={18}/></a>}/>{partnerResult.failed?<EmptyState title={d.unavailable}/>:<PartnerStrip partners={partnerResult.rows} locale={locale}/>}</Container></Section>
 <Section tone="navy" className="home-join"><Container><div><p className="home-kicker">UFDE · UKRAINE · FRANCE</p><h2>{h.join}</h2><p>{h.joinText}</p></div><PrimaryButton href={href('/contact')}>{h.joinButton}<ArrowRight size={18}/></PrimaryButton></Container></Section><Container><p className="home-photo-credit">{d.photo}: <a href={hero.source}>{hero.credit}</a>{hero.license&&<> · <a href={hero.license}>CC BY-SA 2.0</a></>} · {d.cropped}</p></Container></div>;
}
