import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,ArrowUpRight,Microscope,Lightbulb,Landmark} from 'lucide-react';
import {type Locale} from '@ufde/config';
import {dictionary,localizedPath} from '@ufde/config/messages';
import {Eyebrow} from '@ufde/ui';
import {getHero} from '@/lib/content';
export const areaIcons=[Microscope,Lightbulb,Landmark];
export async function Home({locale}:{locale:Locale}){const d=dictionary(locale);const hero=await getHero();const href=(path:string)=>localizedPath(locale,path);return <><section className="hero"><Image src={hero.src} alt={hero.alt} fill priority sizes="100vw"/><div className="hero-shade"/><div className="container hero-content"><Eyebrow>{d.hero[0]}</Eyebrow><h1>{d.hero[1]}<br/>{d.hero[2]} <em>{d.hero[3]}</em></h1><p>{d.fullName}</p><div className="actions"><Link className="button gold" href={href('/about')}>{d.hero[4]} <ArrowRight size={19}/></Link><Link className="hero-link" href={href('/strategic-areas')}>{d.hero[5]} <ArrowUpRight size={18}/></Link></div></div><div className="hero-caption">PARIS, FRANCE <span>01 — {d.hero[0]}</span></div></section><div className="mission-bar"><div className="container"><span>{d.mission[0]}</span><span>{d.mission[1]} <ArrowRight size={20}/></span></div></div><section className="section container intro"><div><Eyebrow>{d.intro[0]}</Eyebrow><h2>{d.intro[1]}<br/>{d.intro[2]}</h2></div><div><p className="lead">{d.intro[3]}</p><p>{d.intro[4]}</p><Link className="text-link" href={href('/about')}>{d.intro[5]} <ArrowUpRight size={18}/></Link></div></section><section className="section soft"><div className="container"><div className="section-heading"><div><Eyebrow>{d.focus[0]}</Eyebrow><h2>{d.focus[1]}</h2></div><Link className="text-link" href={href('/strategic-areas')}>{d.focus[2]} <ArrowRight size={18}/></Link></div><div className="focus-grid">{d.areas.map(([title,body],i)=>{const I=areaIcons[i];return <Link href={href('/strategic-areas')+'#area-'+(i+1)} className="focus-card" key={title}><div className="card-top"><I size={32} strokeWidth={1.4}/><span>0{i+1}</span></div><h3>{title}</h3><p>{body}</p><ArrowUpRight className="card-arrow" size={24}/></Link>})}</div></div></section><section className="section container"><div className="contact-band"><div><Eyebrow>{d.connect[0]}</Eyebrow><h2>{d.connect[1]}<br/>{d.connect[2]}</h2></div><Link className="button gold" href={href('/contact')}>{d.connect[3]} <ArrowRight size={20}/></Link></div><p className="photo-credit">{d.photo}: <a href={hero.source}>{hero.credit}</a> {hero.license&&<>· <a href={hero.license}>CC BY-SA 2.0</a></>} · {d.cropped}</p></section></>}
