import Image from 'next/image';
import {getPartnerLabel} from '@/lib/content';
import {ArrowRight} from 'lucide-react';
import {institute,type Locale} from '@ufde/config';
import {aboutProfile} from '@ufde/config/about';
import type {ContentRecord,ProjectDetails} from '@ufde/types';
import {dictionary,localizedPath} from '@ufde/config/messages';
import {projectLabels,projectPeriod} from '@ufde/config/projects';
import {Container,Section,Breadcrumbs,Heading1,Heading2,SectionHeading,PrimaryButton,EmptyState,StatusBadge,PDFDownload,ProjectMetadata} from '@ufde/ui';
import {getProjects,getProjectDetails,listContent,safeImage} from '@/lib/content';
import {ProjectGrid,ProjectStatusBadge} from './project-grid';
import {PartnerStrip} from './partner-strip';
import {ActivityCarousel} from './activity-carousel';
export async function Projects({locale,item}:{locale:Locale;item?:ContentRecord}){
 const partnerTitle=await getPartnerLabel(locale);
 const l=projectLabels[locale],d=dictionary(locale),href=(p:string)=>localizedPath(locale,p),hero=aboutProfile.photos[0];
 const result=item?{rows:[],failed:false}:await getProjects(locale).then(rows=>({rows,failed:false})).catch(()=>({rows:[],failed:true}));
 const featured=result.rows.find(p=>p.details.featured),p=item?await getProjectDetails(item.slug,locale):null;
 const photo=item?.image&&safeImage(item.image.url)?item.image:{url:hero.url,alt:hero.alt};
 const related=p?.relatedActivitySlugs.length?await listContent('ACTIVITY',locale).then(rows=>rows.filter(r=>p.relatedActivitySlugs.includes(r.slug)).map(r=>({...r,image:r.image&&safeImage(r.image.url)?r.image:null}))):[];
 const metadata=(details:ProjectDetails)=>[{label:l.period,value:projectPeriod(details,locale)},{label:l.partners,value:details.partners.map(x=>x.name).join(' · ')||l.pending},{label:l.area,value:details.strategicArea||l.pending}];
 return <div className="projects-page"><section className="projects-hero"><Image src={photo.url} alt={photo.alt} fill priority sizes="100vw"/><div className="projects-shade"/><Container><Breadcrumbs items={[{label:d.nav[0],href:href('')},{label:d.pages.projects[0],...(item?{href:href('/projects')}:{})},...(item?[{label:item.title}]:[])]}/>{item&&<ProjectStatusBadge status={p?.status} locale={locale}/>}<Heading1>{item?.title||l.title}</Heading1><p>{item?.summary||l.subtitle}</p>{item?.isDemo&&<StatusBadge tone="demo">{l.demo}</StatusBadge>}</Container></section>
 {!item?<><Section><Container>{result.failed?<EmptyState title={d.unavailable}/>:<ProjectGrid projects={result.rows} locale={locale}/>}</Container></Section>{featured&&<Section tone="soft"><Container><div className="project-featured"><div className="project-featured-image">{featured.record.image&&<Image src={featured.record.image.url} alt={featured.record.image.alt} fill sizes="(max-width:800px) 100vw, 50vw"/>}</div><div><p className="eyebrow">{l.featured}</p>{featured.record.isDemo&&<StatusBadge tone="demo">{l.demo}</StatusBadge>}<Heading2>{featured.record.title}</Heading2><p>{featured.record.summary}</p><ProjectMetadata items={metadata(featured.details)}/><PrimaryButton href={href('/projects/'+featured.record.slug)}>{l.view}<ArrowRight size={18}/></PrimaryButton></div></div></Container></Section>}</>:p&&<><Section><Container><ProjectMetadata items={[...metadata(p),{label:l.lead,value:p.lead||l.pending},{label:l.countries,value:p.countries.join(' · ')||l.pending}]}/><div className="project-detail-sections">{[{title:l.background,rows:p.background?[p.background]:[]},{title:l.objectives,rows:p.objectives},{title:l.activities,rows:p.activities},{title:l.outcomes,rows:p.outcomes}].map(({title,rows})=><section key={title}><SectionHeading title={title} underline/>{rows.length?rows.map((text,i)=><p key={i}>{text}</p>):<p>{l.unpublished}</p>}</section>)}</div></Container></Section><Section tone="soft"><Container><SectionHeading title={partnerTitle} underline/>{p.partners.length?<PartnerStrip partners={p.partners} locale={locale} grid label={partnerTitle}/>:<EmptyState title={l.unpublished}/>}</Container></Section><Section><Container><SectionHeading title={l.resources} underline/>{p.resources.length?<div className="project-resources">{p.resources.map(r=>r.format==='PDF'?<PDFDownload key={r.url} href={r.url} label={r.title}/>:<a key={r.url} href={r.url} target="_blank" rel="noopener noreferrer">{r.title}<ArrowRight size={18}/></a>)}</div>:<EmptyState title={l.unpublished}/>}</Container></Section><Section tone="soft"><Container><SectionHeading title={l.related} underline/>{related.length?<ActivityCarousel records={related} locale={locale} filters={false}/>:<EmptyState title={l.unpublished}/>}</Container></Section><Section><Container><SectionHeading title={l.contact} underline/><a className="project-learn" href={'mailto:'+(p.contactEmail||institute.email)}>{p.contactEmail||institute.email}<ArrowRight size={18}/></a></Container></Section></>}
 <section className="project-cta"><Image src={institute.hero.src} alt="" fill sizes="100vw"/><div className="projects-shade"/><Container><div><Heading2>{l.cta}</Heading2><p>{l.ctaText}</p></div><PrimaryButton href={href('/contact')}>{l.ctaButton}<ArrowRight size={18}/></PrimaryButton></Container></section><Container><p className="home-photo-credit">{photo.url===hero.url&&<><a href={hero.source}>{hero.alt} — {hero.credit}</a> · <a href={hero.licenseUrl}>{hero.licenseLabel}</a> · </>}<a href={institute.hero.source}>{institute.hero.credit}</a> · <a href={institute.hero.license}>CC BY-SA 2.0</a> · {d.cropped}</p></Container></div>;
}
