import Image from 'next/image';
import type {Locale} from '@ufde/config';
import type {Publication} from '@ufde/types';
import {aboutProfile} from '@ufde/config/about';
import {dictionary,localizedPath} from '@ufde/config/messages';
import {publicationLabels,publicationTypes} from '@ufde/config/publications';
import {Container,Section,Breadcrumbs,Heading1,SectionHeading,PublicationMetadata,PDFDownload,OutlineButton,EmptyState} from '@ufde/ui';
import {listPublications} from '@/lib/content';
import {PublicationCover,PublicationGrid} from './publication-grid';
export async function Publications({locale,item}:{locale:Locale;item?:Publication}){
 const l=publicationLabels[locale],d=dictionary(locale),href=(p:string)=>localizedPath(locale,p),hero=aboutProfile.photos[1];
 const result=await listPublications(locale).then(items=>({items,failed:false})).catch(()=>({items:[],failed:true}));
 const related=result.items.filter(p=>p.slug!==item?.slug).sort((a,b)=>Number(b.type===item?.type)-Number(a.type===item?.type)).slice(0,4);
 return <div className="publications-page">{!item?<><section className="publications-hero"><Image src={hero.url} alt={hero.alt} fill priority sizes="100vw"/><div className="publications-shade"/><Container><Breadcrumbs items={[{label:d.nav[0],href:href('')},{label:l.title}]}/><Heading1>{l.title}</Heading1><p>{l.subtitle}</p></Container></section><Section><Container>{result.failed?<EmptyState title={d.unavailable}/>:<PublicationGrid items={result.items} locale={locale}/>}</Container></Section><Container><p className="home-photo-credit"><a href={hero.source}>{hero.alt} — {hero.credit}</a> · <a href={hero.licenseUrl}>{hero.licenseLabel}</a> · {d.cropped}</p></Container></>:<><Section tone="soft"><Container><Breadcrumbs items={[{label:d.nav[0],href:href('')},{label:l.title,href:href('/publications')},{label:item.title}]}/><div className="publication-detail-top"><PublicationCover item={item} locale={locale} priority/><div><p className="publication-type">{l.types[publicationTypes.indexOf(item.type)]}</p><Heading1>{item.title}</Heading1><PublicationMetadata items={[{label:l.authors,value:item.authors.join(', ')||l.pending},{label:l.date,value:item.publishedAt?new Intl.DateTimeFormat(locale,{dateStyle:'long',timeZone:'UTC'}).format(new Date(item.publishedAt)):item.year||l.pending},{label:l.language,value:item.language},...(item.doi?[{label:'DOI',value:item.doi}]:[]),...(item.isbn?[{label:'ISBN',value:item.isbn}]:[])]}/><div className="uf-actions">{item.pdfUrl&&<PDFDownload href={item.pdfUrl} label={l.pdf}/>} {item.externalUrl&&<OutlineButton href={item.externalUrl} target="_blank" rel="noopener noreferrer">{l.online}</OutlineButton>}</div></div></div></Container></Section><Section><Container><div className="publication-detail-text">{[{title:l.abstract,text:item.abstract},{title:l.executive,text:item.executiveSummary||l.noSummary},{title:l.citation,text:item.citation||l.noCitation}].map(s=><section key={s.title}><SectionHeading title={s.title} underline/>{s.text.split(/\n\n/).map((p,i)=><p key={i}>{p}</p>)}</section>)}<section><SectionHeading title={l.authors} underline/>{item.authors.length?<ul>{item.authors.map((a,i)=><li key={i}>{a}</li>)}</ul>:<p>{l.pending}</p>}</section></div></Container></Section><Section tone="soft"><Container><SectionHeading title={l.related} underline/>{result.failed?<EmptyState title={d.unavailable}/>:related.length?<PublicationGrid items={related} locale={locale} filters={false}/>:<EmptyState title={l.noRelated}/>}</Container></Section></>}</div>;
}
