import Link from 'next/link';
import Image from 'next/image';
import {Mail,MapPin,Phone} from 'lucide-react';
import {institute,type Locale} from '@ufde/config';
import {dictionary,localizedPath} from '@ufde/config/messages';
import {Navigation} from './navigation';
import {navPaths} from '@/lib/navigation';
import {EnquiryForm} from './forms';
import {demoMode} from '@/lib/content';
export function Header({locale='en',path=''}:{locale?:Locale;path?:string}){const d=dictionary(locale);return <><a className="skip" href="#main">{d.skip}</a><header className="header"><div className="container header-inner"><Link href={localizedPath(locale)} className="wordmark" aria-label={'UFDE — '+d.nav[0]}>{institute.logo.supplied?<Image src={institute.logo.light} alt="UFDE" width={180} height={55}/>:<>UFDE<span>{locale==='uk'?'УКРАЇНСЬКО-ФРАНЦУЗЬКИЙ ІНСТИТУТ':locale==='fr'?'INSTITUT UKRAINO-FRANÇAIS':'UKRAINIAN–FRENCH INSTITUTE'}</span></>}</Link><Navigation locale={locale} path={path} d={d}/></div></header></>}
export function Footer({locale='en'}:{locale?:Locale}){const d=dictionary(locale);const legal=['governance-transparency','legal-notice','privacy','cookies','terms'] as const;return <footer><div className="container footer-grid"><div><p className="footer-wordmark">UFDE</p><p>{d.fullName}</p><p className="muted">{d.mission[0]}</p><p className="social-pending">{d.footer[6]}</p></div><div><h3>{d.footer[0]}</h3>{navPaths.slice(1).map((h,i)=><Link key={h} href={localizedPath(locale,h)}>{d.nav[i+1]}</Link>)}</div><div><h3>{d.footer[1]}</h3><Link href={localizedPath(locale,'/strategic-areas')}>{d.pages['strategic-areas'][0]}</Link><Link href={localizedPath(locale,'/governance-transparency')}>{d.pages['governance-transparency'][0]}</Link><h3 className="contact-subtitle">{d.footer[2]}</h3><p><MapPin size={16}/>{institute.location}</p><a href={'mailto:'+institute.email}><Mail size={16}/>{institute.email}</a><a href={'tel:'+institute.phone.replaceAll(' ','')}><Phone size={16}/>{institute.phone}</a></div><div><h3>{d.footer[3]}</h3><p>{d.footer[4]}</p><EnquiryForm newsletter locale={locale} d={d.form} demo={demoMode}/></div></div><div className="container footer-bottom"><span>© 2026 UFDE. {d.footer[5]}</span><div>{legal.map(k=><Link key={k} href={localizedPath(locale,'/'+k)}>{d.pages[k][0]}</Link>)}</div></div></footer>}
export function PreviewNotice({locale}:{locale:Locale}){return demoMode?<div className="preview-notice">{dictionary(locale).preview}</div>:null}
