import 'reflect-metadata';
import test from 'node:test';
import assert from 'node:assert/strict';
import {ConfigService} from '@nestjs/config';
import {createHmac} from 'node:crypto';
import {FormsController} from '../src/forms.controller';
import {ContactMailService} from '../src/contact-mail.service';
import {contactClientIp} from '../src/contact-security';
function database(){const values=new Map<string,any>(),contacts=new Map<string,any>();const db:any={siteSetting:{findUnique:async({where}:any)=>values.has(where.key)?{key:where.key,value:values.get(where.key)}:null,create:async({data}:any)=>{values.set(data.key,data.value);return data},upsert:async({where,create,update}:any)=>{values.set(where.key,values.has(where.key)?update.value:create.value)},update:async({where,data}:any)=>{values.set(where.key,data.value)},delete:async({where}:any)=>values.delete(where.key),deleteMany:async()=>({count:0}),findMany:async()=>[...values].filter(([k,v])=>k.startsWith('contact-mail:')&&['queued','processing'].includes(v.state)).map(([key,value])=>({key,value}))},contactSubmission:{create:async({data}:any)=>{const r={...data,id:String(contacts.size+1)};contacts.set(r.id,r);return r},findUnique:async({where}:any)=>contacts.get(where.id)},$queryRaw:async()=>[]};db.$transaction=async(fn:any)=>{const before=new Map(values),saved=new Map(contacts);try{return await fn(db)}catch(e){values.clear();contacts.clear();for(const [k,v] of before)values.set(k,v);for(const [k,v] of saved)contacts.set(k,v);throw e}};return {db,values,contacts};}
const message={name:'Test Sender',email:'test@example.org',subject:'Test enquiry',message:'A sufficiently detailed test message.',locale:'en'};
const request=(ip='127.0.0.1')=>({ip,socket:{},header:()=>undefined} as any);
test('contact stores once, queues notification, and acknowledgement is opt-in',async()=>{const {db,values,contacts}=database(),c=new FormsController(db,new ConfigService({CONTACT_RATE_SECRET:'test'}),{processPending:async()=>{}} as any);const a=await c.contact(message,request());const b=await c.contact(message,request());assert.equal(a.reference,b.reference);assert.equal(contacts.size,1);assert.equal([...values.keys()].filter(k=>k.startsWith('contact-mail:')).length,1);await c.contact({...message,message:message.message+' Second',acknowledgement:true},request());assert.equal([...values.keys()].filter(k=>k.startsWith('contact-mail:')).length,3);assert.ok([...contacts.values()].every(r=>r.consentVersion==='privacy-notice-2026-09'));});
test('persistent email and IP limits reject excess requests without storing them',async()=>{for(const sameEmail of [true,false]){const {db,contacts}=database(),c=new FormsController(db,new ConfigService({CONTACT_RATE_SECRET:'test'}),{processPending:async()=>{}} as any);const limit=sameEmail?3:5;for(let i=0;i<limit;i++)await c.contact({...message,email:sameEmail?message.email:`test${i}@example.org`,message:message.message+i},request());await assert.rejects(c.contact({...message,email:sameEmail?message.email:'excess@example.org',message:message.message+' excess'},request()),(e:any)=>e.status===429);assert.equal(contacts.size,limit);}});
test('email failures remain queued and retry with the same idempotency key',async()=>{const {db,values,contacts}=database();contacts.set('1',{...message,id:'1'});values.set('contact-mail:1:notify',{reference:'1',kind:'notify',state:'queued',attempts:0,nextAt:0,createdAt:Date.now()});const keys:string[]=[];const original=globalThis.fetch;let success=false;globalThis.fetch=(async(_url:any,options:any)=>{keys.push(options.headers['Idempotency-Key']);const payload=JSON.parse(options.body);assert.equal(payload.reply_to,message.email);assert.ok(!payload.html);return {ok:success}}) as any;try{const service=new ContactMailService(db,new ConfigService({RESEND_API_KEY:'test',CONTACT_FROM_EMAIL:'office@example.org'}));await service.processPending();assert.equal(values.get('contact-mail:1:notify').state,'queued');values.get('contact-mail:1:notify').nextAt=0;success=true;await service.processPending();assert.equal(values.get('contact-mail:1:notify').state,'sent');assert.deepEqual(keys,['contact-mail:1:notify','contact-mail:1:notify']);}finally{globalThis.fetch=original}});
test('untrusted proxy headers cannot bypass IP limits',()=>{const secret='test-secret',ip='192.0.2.1',time=String(Date.now());let signature='a'.repeat(64);const req={ip:'127.0.0.1',socket:{},header:(k:string)=>({'x-ufde-ip':ip,'x-ufde-time':time,'x-ufde-signature':signature}[k])} as any;assert.equal(contactClientIp(req,secret),'127.0.0.1');signature=createHmac('sha256',secret).update(time+'\n'+ip).digest('hex');assert.equal(contactClientIp(req,secret),ip);});
