INSERT INTO "Media" ("id","slug","url","filename","mimeType","sizeBytes","width","height","sha256","visibility","purpose","updatedAt") VALUES ('portrait-kateryna-hannouf-v2-png','portrait-kateryna-hannouf-v2-png','/images/team/kateryna-hannouf-v2.png','kateryna-hannouf-v2.png','image/png',359324,594,620,'e1344b929693c5c2433fcba9f00e4c31d8599f2c39da97d8b34e17a00f619b5f','PUBLIC','PORTRAIT',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "TeamMember" SET "portraitId"=(SELECT "id" FROM "Media" WHERE "slug"='portrait-kateryna-hannouf-v2-png'),"updatedAt"=CURRENT_TIMESTAMP WHERE "slug"='kateryna-hannouf';
UPDATE "TeamMemberTranslation" SET "portraitAlt"='Kateryna Hannouf',"updatedAt"=CURRENT_TIMESTAMP WHERE "teamMemberId" IN (SELECT "id" FROM "TeamMember" WHERE "slug"='kateryna-hannouf');
INSERT INTO "Media" ("id","slug","url","filename","mimeType","sizeBytes","width","height","sha256","visibility","purpose","updatedAt") VALUES ('portrait-volodymyr-kogutyak-v2-jpg','portrait-volodymyr-kogutyak-v2-jpg','/images/team/volodymyr-kogutyak-v2.jpg','volodymyr-kogutyak-v2.jpg','image/jpeg',122866,1075,1162,'f97ea5b82ab7a27722c44a196684f0852e33b9e594254e7a559f4b64113378af','PUBLIC','PORTRAIT',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "TeamMember" SET "portraitId"=(SELECT "id" FROM "Media" WHERE "slug"='portrait-volodymyr-kogutyak-v2-jpg'),"updatedAt"=CURRENT_TIMESTAMP WHERE "slug"='volodymyr-kohutiak';
UPDATE "TeamMemberTranslation" SET "portraitAlt"='Volodymyr Kogutyak',"updatedAt"=CURRENT_TIMESTAMP WHERE "teamMemberId" IN (SELECT "id" FROM "TeamMember" WHERE "slug"='volodymyr-kohutiak');
INSERT INTO "Media" ("id","slug","url","filename","mimeType","sizeBytes","width","height","sha256","visibility","purpose","updatedAt") VALUES ('portrait-anna-golovkova-jpg','portrait-anna-golovkova-jpg','/images/team/anna-golovkova.jpg','anna-golovkova.jpg','image/jpeg',15494,200,200,'739ed133c9170515337b9750e6cbb4fd1ccc1e4508f19da245d83fc7b3a8f57e','PUBLIC','PORTRAIT',CURRENT_TIMESTAMP) ON CONFLICT ("slug") DO NOTHING;
UPDATE "TeamMember" SET "portraitId"=(SELECT "id" FROM "Media" WHERE "slug"='portrait-anna-golovkova-jpg'),"updatedAt"=CURRENT_TIMESTAMP WHERE "slug"='anna-golovkova';
UPDATE "TeamMemberTranslation" SET "portraitAlt"='Anna Golovkova',"updatedAt"=CURRENT_TIMESTAMP WHERE "teamMemberId" IN (SELECT "id" FROM "TeamMember" WHERE "slug"='anna-golovkova');
